name: Notify Teams on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Teams
        uses: fjogeleit/http-request-action@v1.15.1
        with:
          url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          method: POST
          contentType: application/json
          data: |
            {
              "type": "message",
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "contentUrl": null,
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": [
                      {
                        "type": "TextBlock",
                        "text": "📌Nouvelle Pull Request by ${{ github.actor }}",
                        "weight": "Bolder",
                        "size": "Large"
                      },
                      {
                        "type": "FactSet",
                        "facts": [
                          {
                            "title": "Title:",
                            "value": "${{ github.event.pull_request.title }}"
                          },
                          {
                            "title": "Branch:",
                            "value": "${{ github.event.pull_request.head.ref }}"
                          },
                        ]
                      },
                      "actions": [
                        {
                          "type": "Action.OpenUrl",
                          "url": "${{ github.event.pull_request.html_url }}",
                          "title": "Voir la Pull request"
                        }
                      ]
                    ]
                  }
                }
              ]
            }
